#!/bin/bash

compile () {
  # copy all files in the current directory to the keymaps directory inside the
  # copy of qmk_firmware in the current directory
  pushd ~/git/atreus-keymap
  mkdir -p ./qmk_firmware/keyboards/atreus/keymaps/splintax
  cp *.* ./qmk_firmware/keyboards/atreus/keymaps/splintax
  # change into the qmk_firmware directory, update it and build it
  pushd qmk_firmware
  git pull
  make atreus:splintax
  popd; popd
}

flash () {
  pushd ~/git/atreus-keymap/qmk_firmware/.build
  # uncomment the following lines if you have problems with /dev/ttyACM0:
  # systemctl stop ModemManager.service
  filename=atreus_astar_splintax.hex
  if [ ! -f "$filename" ]; then
    echo "Couldn't find firmware; aborting rather than bricking keyboard."
    exit
  fi
  avrdude -p atmega32u4 -c avr109 \
    -U flash:w:"$filename" \
    -P /dev/ttyACM0
  popd
}

#compile
#if [[ $? && $1 = "--flash" ]]; then flash; fi
